### ISSUE TITLE
Openhab 3.3.0 RC1

### ISSUE THREAD

**Issue by blue-danube-vienna** [jeroenhendricksen/node-red-contrib-openhab3#38] opened 2022-06-26 15:49 UTC
Since 3.3.0~M7-1 [node-red-contrib-openhab3] the openhab-in-nodedoesn't work anymore.
The node does not receive a new status...
In Openhab 3.3.0 RC1 -> the same error.

node-red-contrib-openhab2 from Peter De Mangelaere has the same problem.

Downgrade to  3.2.0 solves that

best regards

**Comment by jeroenhendricksen** [comment] 2022-06-27 07:06
> Since 3.3.0~M7-1 [node-red-contrib-openhab3] the openhab-in-nodedoesn't work anymore. The node does not receive a new status... In Openhab 3.3.0 RC1 -> the same error.
> 
> node-red-contrib-openhab2 from Peter De Mangelaere has the same problem.
> 
> Downgrade to 3.2.0 solves that
> 
> best regards

Thank you for notifying. When I have time, I will try to add support for 3.3.x

**Comment by SeveranExp** [comment] 2022-06-27 18:27
Can confirm the situation, I am suffering the same .
Wasn’t aware about this node. @jeroenhendricksen  what would be your suggestion to migrate from pd’s node to yours??

**Comment by dorcari** [comment] 2022-06-27 18:59
@jeroenhendricksen  I've done exactly that (export and change names) with success. 

Having the same problem as @SeveranExp and @blue-danube-vienna on openhab items not updating in node-red, I'll eagerly be waiting for your update ;)

**Comment by dorcari** [comment] 2022-06-27 20:53
My feedback is the same as @SeveranExp

**Comment by RobertHerter** [comment] 2022-06-28 06:57
Notfixing for me too.

Updates only on startup.

**Comment by jeroenhendricksen** [comment] 2022-06-28 07:42
Thank you for the feedback. Its unfortunate that it doesn't yet work for updates after startup. When I tested with my docker test setup (which is part of the repo) it seemed to work for OH 3.2 and OH 3.3, but I might have missed your testcase. I'll have another look at it.

**Comment by BigDi** [comment] 2022-06-28 08:42
I can confirm that only on start up the state is updated.

**Comment by jeroenhendricksen** [comment] 2022-06-28 18:37
Ok, I'm testing this again and I cannot find the problem you are describing. You indicate that the state is only updated on startup, but in my test setup that does seem to work properly, which means the items updates sent out via SSE (Server Sent Events) are properly received.

I need to know more about your setup(s). What exactly are you doing to cause the problem to appear? Maybe its not included in my test setup...

So I've loaded my test setup (all in docker), a nodered instance talking to openhab 3.2 (no authentication), 3.3 (no authentication) and 3.3 with authentication using an api token. 

Look at the screenshot below:

<img width="1737" alt="Screenshot 2022-06-28 at 20 33 32" src="https://user-images.githubusercontent.com/32140294/176256999-9947f8b7-dcd1-45b7-a703-9cdf0bbde492.png">

For OH v33, whenever I send out an update via an out2 node (using a PUT request), it is received by the in2 node (via a Server-Sent Events connection to `http://localhost:8083/rest/events`). Also, when restarting the flow (deployed after changes), the InitialStateEvent is properly outputted and printed in the debug pane.
In case you want to reproduce or verify, my changes are on branch `master-oh33-tests`.

What use case am I missing? Or what is special about your setups?

**Comment by dorcari** [comment] 2022-06-28 18:53
Events,monitor and out nodes are working, the problem is on the openhab in node, it updates on deploy but after that it doesn't update any more, in openhab I'm changing the state of a switch but it doesn't update the node in node red. In a few minutes I can send you a flow.

**Comment by jeroenhendricksen** [comment] 2022-06-28 19:54
I won't quote you known because that would make stuff unreadable.

We could get on a discord, but I need some clarifications first.

What are the settings of the in2 node set to?
What about the nodered service output? Does it show something like this? What does it show exactly?
```
27 Jun 20:14:08 - [info] [openhab2-controller2:openhab v3.3] Opened connection to http://openhab33:8080/rest/events?topics=openhab/items
27 Jun 20:14:08 - [info] [openhab2-controller2:openhab v3.3] Connection established. Emitting 11 InitialEvents.
```

I've also tested with my TestSwitch. When I switch it, I receive the following events via `http://localhost:8083/rest/events`:
```
event: message
data: {"topic":"openhab/items/TestSwitch/state","payload":"{\"type\":\"OnOff\",\"value\":\"ON\"}","type":"ItemStateEvent"}

event: message
data: {"topic":"openhab/items/TestSwitch/statechanged","payload":"{\"type\":\"OnOff\",\"value\":\"ON\",\"oldType\":\"UnDef\",\"oldValue\":\"NULL\"}","type":"ItemStateChangedEvent"}

event: message
data: {"topic":"openhab/items/TestSwitch/command","payload":"{\"type\":\"OnOff\",\"value\":\"OFF\"}","type":"ItemCommandEvent"}

event: message
data: {"topic":"openhab/items/TestSwitch/state","payload":"{\"type\":\"OnOff\",\"value\":\"OFF\"}","type":"ItemStateEvent"}

event: message
data: {"topic":"openhab/items/TestSwitch/statechanged","payload":"{\"type\":\"OnOff\",\"value\":\"OFF\",\"oldType\":\"OnOff\",\"oldValue\":\"ON\"}","type":"ItemStateChangedEvent"}
```

So triggering the item from openhab33 (http://localhost:8083) does work in my case. I'm thinking something might be up with your items definitions. Can you look at http://youropenhab:port/rest/events while switching the button in the UI?

**Comment by SeveranExp** [comment] 2022-06-28 20:01
Let's see if I can answer all questions:
This is what I see in node red logs
![image](https://user-images.githubusercontent.com/30979860/176273725-8c74ad54-d6b1-409b-bdad-d5d8915159b6.png)

When I use the inject node and spam the events window i do see it (Sorry about the spam):
![image](https://user-images.githubusercontent.com/30979860/176274013-d275f2b8-bb48-46f7-abee-3f03ef99221b.png)

So the "out" node works. But the "in" does not get the "memo", since:
![image](https://user-images.githubusercontent.com/30979860/176274149-727f0108-d6e5-44cd-a25e-297755a485e4.png)


I'm online right now so let me know if you need more info.

**Comment by jeroenhendricksen** [comment] 2022-06-28 20:06
Thats very helpful. The SSE connection is established. Now what is your in2 node configured for?

<img width="477" alt="Screenshot 2022-06-28 at 22 06 13" src="https://user-images.githubusercontent.com/32140294/176275120-4294259f-9b6b-49f5-ba24-72a246ddc538.png">

**Comment by SeveranExp** [comment] 2022-06-28 20:07
![image](https://user-images.githubusercontent.com/30979860/176275284-e77409e2-0d1e-4fa8-b561-f253f68298a0.png)
Like so ^

**Comment by jeroenhendricksen** [comment] 2022-06-28 20:11
^^ That looks good. The event is distributed via the SSE connection and should have been propagated to the related in2 nodes. Let's get on discord. My username is `randomname#4792`

**Comment by BigDi** [comment] 2022-06-29 10:02
There is already noted a problem and from my point of it looks like this one. It started with 2nd post.
https://community.openhab.org/t/openhab-3-3-release-discussion/136925

**Comment by jeroenhendricksen** [comment] 2022-06-29 11:00
> There is already noted a problem and from my point of it looks like this one. It started with 2nd post. https://community.openhab.org/t/openhab-3-3-release-discussion/136925

I've already addressed the "accept header problem" in [this](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/commit/32399aa11ef91900a7190a58556e30c940f4a56f) commit. This change is applicable to all GET, PUT and POST requests sent from this plugin (`node-red-contrib-openhab3`, NOT `node-red-contrib-openhab2`) towards the openHAB rest api.

I did some further investigation yesterday with SeveranExp and dorcari and the SSE events (for which I didn't change any headers) seem to arrive in the nodered module perfectly fine, but parsing them doesn't forward these messages to the relevant `openhab2-in2` nodes.

First thing on my list is to test my local test setup against a protected OH 3.3 instance that requires the use of an API token. My tests with an unprotected OH 3.3 didn't allow me to reproduce the issue.

**Comment by BigDi** [comment] 2022-06-29 11:10
This issue happend by me after update from OH 3.3 M7 to Release. My OH installation is not protected. I only get a status after starting Node Red. Then I don't get any more updates.

**Comment by mabadil** [comment] 2022-06-29 13:52
> This issue happend by me after update from OH 3.3 M7 to release version. My OH installation is not protected. I only get a status after starting Node Red. Then I don't get any more updates.

also for me

**Comment by jeroenhendricksen** [comment] 2022-06-29 19:53
I found time to do some testing and it seems I can reproduce the problem. I think I've found the problem. 
What seems to happen is that:

```
# does receive the events from openhab v3.2:
curl "http://localhost:8083/rest/events?topics/openhab/items"`
```

```
# doesn't receive the events from openhab v3.3:
curl "http://localhost:8083/rest/events?topics/openhab/items"`
```

```
# but this does receive the events from openhab v3.3`
curl "http://localhost:8083/rest/events"`
```

It seems the topic filtering for /rest/events endpoints works differently since OH 3.3 stable.
Now I can start working on a proper fix.

**Comment by EngiNearEngiFar** [comment] 2022-06-29 20:37
I am wondering why it changed in OH 3.3? There must be a reason for this..?
Also the issue was not easy to find out. So others might have the same problem, when working with the API and an update is done?
Maybe it is a bug OH?

**Comment by SeveranExp** [comment] 2022-06-29 20:40
> I am wondering why it changed in OH 3.3? There must be a reason for this..?
> Also the issue was not easy to find out. So others might have the same problem, when working with the API and an update is done?
> Maybe it is a bug OH?

My only suggestion is to kindly ask @jeroenhendricksen to jump over to the thread I shared above in the openHAB forum to describe the situation in detail and ask if the API is working as intended. Because if it’s a bug and they fix it, it might just break again, and we’d be here all over again.

**Comment by jeroenhendricksen** [comment] 2022-06-29 20:59
I've released 1.4.1. I'm not sure if this fill fix it for your, but it's worth a try. Basically what I changed is that for OH v3 connections, the topics filter is no longer provided in the url.

**Comment by jeroenhendricksen** [comment] 2022-06-29 21:02
> > I am wondering why it changed in OH 3.3? There must be a reason for this..?
> > Also the issue was not easy to find out. So others might have the same problem, when working with the API and an update is done?
> > Maybe it is a bug OH?
> 
> My only suggestion is to kindly ask @jeroenhendricksen to jump over to the thread I shared above in the openHAB forum to describe the situation in detail and ask if the API is working as intended. Because if it’s a bug and they fix it, it might just break again, and we’d be here all over again.

I'm not sure yet. That looks like a very broad topic where a(ny) reply would loose its function very fast. Also I see a lot of reports about completely unrelated issues with regards to this module. I'll focus on fixing the problem for this module first.

**Comment by SeveranExp** [comment] 2022-06-29 21:25
@jeroenhendricksen 
IT'S WORKING!!!!!!!!!

**Comment by SeveranExp** [comment] 2022-06-29 21:29
![2022-06-29_22h24_25](https://user-images.githubusercontent.com/30979860/176548195-4d4d55f9-5943-4a20-8023-725321d3dbc6.gif)
mwuahahahahaha

**Comment by ElTamatsu** [comment] 2022-06-29 23:38
Well, Yannick Schaus mentioned the usage of the API (in face of "/rest/events" and "/rest/events/states/") a few hours ago in the openhab forum as same as @jeroenhendricksen did in here.
[-> link to his post](https://community.openhab.org/t/openhab-3-3-release-discussion/136925/65)
So it's seems to be more likely, that this new way of handling is really intended by the openhab guys.

But what i'm kinda thinking about after read his post is: -> could it be more handy to use the "/rest/events/states/" subscription for the openhab2-in2 node perhaps?
Since the single items to really watch for are known by the user setup of the in2-nodes already ... so isn't it some data overload to stream the whole system item events (while fetching "/rest/events") then? :-\

**Comment by jeroenhendricksen** [comment] 2022-06-30 05:56
> Well, Yannick Schaus mentioned the usage of the API (in face of "/rest/events" and "/rest/events/states/") a few hours ago in the openhab forum as same as @jeroenhendricksen did in here. [-> link to his post](https://community.openhab.org/t/openhab-3-3-release-discussion/136925/65) So it's seems to be more likely, that this new way of handling is really intended by the openhab guys.
> 
> But what i'm kinda thinking about after read his post is: -> could it be more handy to use the "/rest/events/states/" subscription for the openhab2-in2 node perhaps? Since the single items to really watch for are known by the user setup of the in2-nodes already ... so isn't it some data overload to stream the whole system item events (while fetching "/rest/events") then? :-\

Nice suggestion. I've looked at this `/rest/events/states` node, but I don't think it's very useful to this plugin. 
That's because it's not really sending out any useful data?

```
# Opening a stream and then changing many items shows only a single message:
curl "http://localhost:8081/rest/events/states"
event: ready
id: 0
data: 8f27c9f3-bef5-48b7-9400-7046fcc9c025
```

Of course you can use it so subscribe to an item state I think, but it's more efficient to receive all the updates at once (that also include all detailed information of what has changed), given that you are using rather many openhab nodes instead of just a few. Feel free to point out any errors in my comment that's based on a very quick little experiment.

**Comment by BigDi** [comment] 2022-06-30 07:56
Many thanks! Works now.

**Comment by jeroenhendricksen** [comment] 2022-06-30 08:29
@mabadil was this issue fixed for you as well?

**Comment by ElTamatsu** [comment] 2022-06-30 08:34
> Nice suggestion. I've looked at this `/rest/events/states` node, but I don't think it's very useful to this plugin. That's because it's not really sending out any useful data?
> 
> ```
> # Opening a stream and then changing many items shows only a single message:
> curl "http://localhost:8081/rest/events/states"
> event: ready
> id: 0
> data: 8f27c9f3-bef5-48b7-9400-7046fcc9c025
> 
> curl "http://localhost:8081/rest/events/states/8f27c9f3-bef5-48b7-9400-7046fcc9c025"
> ➜  (returns immediately)
> ```

Ooh, as far as i got it right, you have to pass some array of items to watch for too.
The openhab maintainer Yannick Schaus described the usage in a nice way at:
[RFC: flexible API/SSE endpoint for dynamic item state updates #1363](https://github.com/openhab/openhab-core/issues/1363)

But i never tried it myself yet ... so i'm not really sure, if it would be helpful for the node.
And you're rigth. As long as everything works fine already, there is no need for changes. :)
So thx for your work!

**Comment by jeroenhendricksen** [comment] 2022-07-01 10:45
I consider this issue fixed, so I'm closing it.

**Closed by jeroenhendricksen** 2022-07-01 10:45 UTC

**Comment by blue-danube-vienna** [comment] 2022-07-02 10:56
Thank you for very much!
Best regards
