### ISSUE TITLE
Node-red can’t select itemName

### ISSUE THREAD

**Issue by peysche** [jeroenhendricksen/node-red-contrib-openhab3#27] opened 2021-11-29 17:09 UTC
Hi, 

Does not work
OH: openHAB 3.2.0.M4
NR: 2.1.3
NR-LIB: 1.3.28

This Works
OH: openHAB 3.2.0.M4
NR: 1.3.4
NR-LIB: 1.3.28

[Node-red can’t select itemName](https://community.openhab.org/t/node-red-cant-select-itemname/128844)

openhab2-get2 has a problem

Already existing Items are working, but you can not add new ones or change old ones

Also reverting node-red-contrib-openhab3 to 1.3.0 on the Host with NR Version 2.1.3 does not change the behavior

Looks like there is a difference between NR Version 1.3 and 2.1 ...

Regards

**Comment by peysche** [comment] 2021-11-30 13:02
Hi, 

I did some researches, and found out the following error in Development console..

`GET http://mynodered.mydomain.com:1880/openhab3/items?name=smarthome&protocol=http&host=myopenhab.mydomain.com&port=8080&path=&username=&password=&ohversion=v3&token=<-------my token-----> 404 (Not Found)`

when I open the link it will end like this `Cannot GET /openhab3/items`

So I thought about CORS because NodeRed and OpenHab are hosted on different Hosts

the following settings are dependent on OpenHab version set and working

`org.eclipse.smarthome.cors.enable=true`
`org.openhab.cors:enable=true`

And CORS will also effect the version 1.3.4 on the working host... so it looks for me something strange is in going on...

can someone give me a hint how i can find logs regarding the `Cannot GET /openhab3/items` .. Thing

if I call the exact same URL from the host with installed NodeRed Version 1.3 I get the Item List ...

So i need to know where the Exception is raised i can not find something in the source of this Node ... could it be that this is somehow triggerd by the used AXIOS component ?? are there somewhere logs ?

Thx

**Comment by peysche** [comment] 2021-12-03 12:05
Hi All,

Found the reason for the problem... 

has nothing todo with the Node or NodeRed !

i am using a Docker Nodered instance in combination with Hassio .. in that case all the NodeRed Entpoints get prefixed with /endpoint/  ... so i had to change
line 545 in 77-openhab2.html from  

`$.getJSON("/openhab3/items", config) `
to
`$.getJSON("/endpoint/openhab3/items", config)
`

Hope this helps someone else doing the same thing and facing the same problem !

Regards

**Comment by jeroenhendricksen** [comment] 2021-12-03 19:30
> Hi All,
> 
> Found the reason for the problem...
> 
> has nothing todo with the Node or NodeRed !
> 
> i am using a Docker Nodered instance in combination with Hassio .. in that case all the NodeRed Entpoints get prefixed with /endpoint/ ... so i had to change line 545 in 77-openhab2.html from
> 
> `$.getJSON("/openhab3/items", config) ` to `$.getJSON("/endpoint/openhab3/items", config) `
> 
> Hope this helps someone else doing the same thing and facing the same problem !
> 
> Regards

Glad you've found it. Maybe I need to add a relative path to the nodered openhab configuration screen plugin to allow for entering a relative path?

**Comment by firstascentak** [comment] 2021-12-05 20:35
I was going to create a new issue but mine is fairly similar to this, except the fix above doesn't work for me. 
But I'm also not using a docker.

I have a fresh VM which hosts Hassio natively. within Hassio I've installed the Node-red add-on. Within Node-red I've installed the openhab3 node.

Node-Red (2.1.4)
openhab3 (1.3.28)
Connecting to OpenHab2, not 3.

The only node I can get to work is Events which does list all of my things/devices. 
When I use In, Get etc the itemName won't update so I can't select an item from the dropdown. Monitor also doesn't work. 
Any tips on where I can look next? In case it matters, I can access and control all of my devices directly in OpenHab2 on the Paper UI. 

![image](https://user-images.githubusercontent.com/35588594/144762883-9e1d9feb-6084-4798-8b1f-e29b7ea6d755.png)

![image](https://user-images.githubusercontent.com/35588594/144762892-75126d4d-5093-4199-a5e5-9df5206d9d28.png)

**Comment by jeroenhendricksen** [comment] 2021-12-06 20:22
A problem with a relative web url link seems a logical explanation, but I'm sad that doesn't help you solve your problem @firstascentak

I was looking at running hassio inside VirtualBox, to see with my own eyes what it does with regards to openhab (v3) related settings, so I guess you'll have to wait for that before I can figure out how to fix this.

**Comment by jeroenhendricksen** [comment] 2021-12-08 19:36
Can you have a look @firstascentak to see wether any of the  `httpNodeRoot`, `httpRoot` or `httpStatic` keys in the Node-Red `settings.js` file might have been set? If so, that would explain a lot and help me with an appropriate fix.

**Comment by firstascentak** [comment] 2021-12-08 20:36
`httpRoot` and `httpStatic` are commented out. There is a comment/note stating `httpNodeRoot` is controlled by the home assistant add-on and removed. The additional note in settings.js for httpNodeRoot is
`* - httpNodeRoot (set fixed to '/endpoint' )`


```
//httpRoot: '/red',
//httpStatic: '/home/nol/node-red-static/',
```

This is the config within the node-red add-on
```
certfile: fullchain.pem
credential_secret: ##########
http_node:
  password: ''
  username: ''
http_static:
  password: ''
  username: ''
init_commands: []
keyfile: privkey.pem
npm_packages: []
ssl: false
system_packages: []
theme: default
```

And here is a note on a documentations page within the add-on as well that may or may not hint towards anything?

```
To password protect the node-defined HTTP endpoints (httpNodeRoot), the following properties can be used:

username
password
Note: In order to use the http_node you will need to expose Node-RED using a network port in addition to ingress. The HTTP nodes will also be presented under /endpoint/ as shown in the UI. If using the node-red-dashboard module this will also be hosted under this path and will use any credentials set here.

Option: http_static

To password protect the static content (httpStatic), the following properties can be used:

username
password

```

**Comment by jeroenhendricksen** [comment] 2021-12-08 20:51
Great, thank you for sharing this. This means that @peysche was correct in how to "fix" this for Node-Red being installed ad add-on into Hassio and now I understand his hardcoded fix. I'll see if I can make the items part (`$.getJSON("/openhab3/items", config)`) more dynamic.

**Comment by jeroenhendricksen** [comment] 2021-12-09 07:59
I've release version 1.3.29 of the plugin and would like you to test it and tell me if it works for you from the HASS IO setup. I've manually tested it while the `httpRoot` setting was changed in Node-RED and that seemed to work, but I'm not sure about changes to the `httpNodeRoot` setting. I can't easily detect it from the Node-RED UI, because it seems the Node-RED url is still ending with `/` and not `/endpoint`

**Comment by firstascentak** [comment] 2021-12-10 01:09
Excellent! Thanks for updating that quickly. I've been slammed today but I should be able to test this tomorrow and provide some feedback.

**Comment by firstascentak** [comment] 2021-12-11 00:27
hmmm, still a no go for me. But, with that being said, even with the previous version 1.3.28, it wasn't working for me either when I manually tried @peysche fix by editing the 77-openhab2.html file to add /endpoint/ to the path. So there may be something else going on, at least for me.

I can see changes from IP:8080/rest/items though and I can see them change. hmmm what to try next??

Thank you btw for the quick update to 1.3.29

**Comment by jeroenhendricksen** [comment] 2021-12-13 21:36
> hmmm, still a no go for me. But, with that being said, even with the previous version 1.3.28, it wasn't working for me either when I manually tried @peysche fix by editing the 77-openhab2.html file to add /endpoint/ to the path. So there may be something else going on, at least for me.
> 
> I can see changes from IP:8080/rest/items though and I can see them change. hmmm what to try next??
> 
> Thank you btw for the quick update to 1.3.29

I'm sorry to hear that it doesn't yet work for you. What's next is that you could look into the exact request the openhab node (one that allows you to select from a list of items) makes in the background. You can see the request it makes via the network tab of you browsers developer console (tested with Chrome):

<img width="1759" alt="Screenshot 2021-12-13 at 22 33 43" src="https://user-images.githubusercontent.com/32140294/145892445-61378bac-22e4-4cec-a102-1428e8ca7382.png">

The "get my items"-request is translated to `http://localhost:1880/openhab3/items?name=openhab2&protocol=http&host=openhab2&port=8080&path=&username=&password=&ohversion=v2` and also works when I request it from my local machine and from the docker container. You could try that url from the Hass IO server and see what happens.

**Comment by GledholtHall** [comment] 2021-12-22 05:24
Im having this same issue - select item is greyed out..  HASSIO container - tried the edit but no joy.

I am using OpenHAB 3.2 release - should I be selecting v3 in this node and also including the oAuth key ?  It seems I dont need the username and password but OH asks you to select a user when creating the key ??

**Comment by jeroenhendricksen** [comment] 2021-12-23 16:18
> Im having this same issue - select item is greyed out.. HASSIO container - tried the edit but no joy.
> 
> I am using OpenHAB 3.2 release - should I be selecting v3 in this node and also including the oAuth key ? It seems I dont need the username and password but OH asks you to select a user when creating the key ??

After a clean install, OpenHAB 3 asks you to create a new user. The user password is NOT the token. You need to create an API "oAuth" key related to the user account. Don't mix up the username/password for OpenHAB itself with the username/password you can set in an OpenHAB connection in Node-RED, the latter is only for when you have basic authentication (via a reverse proxy) in place. I'm not aware of anyone actually using that "basic authentication" feature, but it was there already when I copied this plugin.

**Comment by GledholtHall** [comment] 2021-12-27 06:12
I am not confusing the two.. I using  the very long key that is generated and only shown once.   I have been leaving the username and password in the connection in NodeRED blank but included the oAuth token. I can’t get items populated it remains greyed out. I have tried without the oAuth token too

**Comment by lampy2** [comment] 2021-12-27 06:46
Did you tried already to fill in the token in the username box only? Leave the password and oAuth empty.
[link oh docs ](https://www.openhab.org/docs/configuration/apitokens.html)

**Comment by jeroenhendricksen** [comment] 2021-12-27 09:58
> link oh docs

That does not work(!). That documentation references [another plugin](https://flows.nodered.org/node/node-red-contrib-openhab2), not [this one](https://github.com/jeroenhendricksen/node-red-contrib-openhab3).

> I am not confusing the two.. I using the very long key that is generated and only shown once. I have been leaving the username and password in the connection in NodeRED blank but included the oAuth token. I can’t get items populated it remains greyed out. I have tried without the oAuth token too

So I am aware that it doesn't work with HASSIo and I would like to fix it, but I'm asking for more information from someone experiencing the bug as I can't reproduce it. See [this comment](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/issues/27#issuecomment-992932873).

**Comment by firstascentak** [comment] 2021-12-28 03:42
> > hmmm, still a no go for me. But, with that being said, even with the previous version 1.3.28, it wasn't working for me either when I manually tried @peysche fix by editing the 77-openhab2.html file to add /endpoint/ to the path. So there may be something else going on, at least for me.
> > I can see changes from IP:8080/rest/items though and I can see them change. hmmm what to try next??
> > Thank you btw for the quick update to 1.3.29
> 
> I'm sorry to hear that it doesn't yet work for you. What's next is that you could look into the exact request the openhab node (one that allows you to select from a list of items) makes in the background. You can see the request it makes via the network tab of you browsers developer console (tested with Chrome):
> 
> <img alt="Screenshot 2021-12-13 at 22 33 43" width="1759" src="https://user-images.githubusercontent.com/32140294/145892445-61378bac-22e4-4cec-a102-1428e8ca7382.png">
> 
> The "get my items"-request is translated to `http://localhost:1880/openhab3/items?name=openhab2&protocol=http&host=openhab2&port=8080&path=&username=&password=&ohversion=v2` and also works when I request it from my local machine and from the docker container. You could try that url from the Hass IO server and see what happens.

Hey Jeroen, so sorry for the delay, my server is at my RV and I was away for a bit, but back on it.
So I looked into the exact request and this is what I see...
![image](https://user-images.githubusercontent.com/35588594/147525421-95bc4abf-b4f9-4260-8a83-d8f353cf449f.png)
First thing I noticed was that my url was slightly different than yours, maybe due to the HassIO install?

![image](https://user-images.githubusercontent.com/35588594/147525510-7b76b55d-306e-4931-9753-4b172697ae0d.png)

When I plug in the URL directly in a browser on my HassIO server...
![image](https://user-images.githubusercontent.com/35588594/147525574-04e0832b-07d3-45e3-bbc4-32edc90bb43a.png)

and of course, all IP addresses are correct and I can see openhab direclty..
![image](https://user-images.githubusercontent.com/35588594/147525713-a6c74399-4e40-4288-88c8-1a390c88d4eb.png)

**Comment by GledholtHall** [comment] 2021-12-29 03:27
I have installed NodeRED on my openHAB  machine and this OH3 node now works well. 
I have installed the HomeAssistant nodes too and those work nicely back to my HA machine.
I would have preferred the other way around as the openHAB machine is a Pi and the HA machine an NUC so more power over there but I'll await developments here and see if the issue gets fixed shortly.

**Comment by GledholtHall** [comment] 2021-12-29 15:33
Well - hopefully..

I  have added the following line to the HA NodeRED config
`leave_front_door_open:_ true`
Also you now have to include the following in the HA NodeRED config  with a password/username value.
```
http_node:
  password: pw
  username: pw
http_static:
  password: pw
  username: pw
```

Then when I next opened the openHAB3 nodes connection configuration which connect to HAserverIP:1880 it popped up a dialog which asked me for a username password - I entered pw pw in my case.  Everything connected and the 'select items' was populated.  Just to be clear I did not enter pw in the username or password field within this node

**Comment by jeroenhendricksen** [comment] 2021-12-29 20:36
> > > hmmm, still a no go for me. But, with that being said, even with the previous version 1.3.28, it wasn't working for me either when I manually tried @peysche fix by editing the 77-openhab2.html file to add /endpoint/ to the path. So there may be something else going on, at least for me.
> > > I can see changes from IP:8080/rest/items though and I can see them change. hmmm what to try next??
> > > Thank you btw for the quick update to 1.3.29
> > 
> > 
> > I'm sorry to hear that it doesn't yet work for you. What's next is that you could look into the exact request the openhab node (one that allows you to select from a list of items) makes in the background. You can see the request it makes via the network tab of you browsers developer console (tested with Chrome):
> > <img alt="Screenshot 2021-12-13 at 22 33 43" width="1759" src="https://user-images.githubusercontent.com/32140294/145892445-61378bac-22e4-4cec-a102-1428e8ca7382.png">
> > The "get my items"-request is translated to `http://localhost:1880/openhab3/items?name=openhab2&protocol=http&host=openhab2&port=8080&path=&username=&password=&ohversion=v2` and also works when I request it from my local machine and from the docker container. You could try that url from the Hass IO server and see what happens.
> 
> Hey Jeroen, so sorry for the delay, my server is at my RV and I was away for a bit, but back on it. So I looked into the exact request and this is what I see... ![image](https://user-images.githubusercontent.com/35588594/147525421-95bc4abf-b4f9-4260-8a83-d8f353cf449f.png) First thing I noticed was that my url was slightly different than yours, maybe due to the HassIO install?
> 
> ![image](https://user-images.githubusercontent.com/35588594/147525510-7b76b55d-306e-4931-9753-4b172697ae0d.png)
> 
> When I plug in the URL directly in a browser on my HassIO server... ![image](https://user-images.githubusercontent.com/35588594/147525574-04e0832b-07d3-45e3-bbc4-32edc90bb43a.png)
> 
> and of course, all IP addresses are correct and I can see openhab direclty.. ![image](https://user-images.githubusercontent.com/35588594/147525713-a6c74399-4e40-4288-88c8-1a390c88d4eb.png)

That's interesting. It seems that you are using "hassio-ingress" which makes node-red available behind some 'weird' url scheme (`/api/hassio_ingress/TOKEN`). This obviously breaks any plugins inside NodeRED that requires a call-back to itself, in case the NodeRED does not know what its 'base url' might be. I'm not yet sure how I can fix that on my side. I'm pretty confident that there are more UI-based node-RED extensions that will break because of this...
I did expect to find some user questions about this issue, but couldn't really find any...

**Comment by firstascentak** [comment] 2021-12-30 01:44
> That's interesting. It seems that you are using "hassio-ingress" which makes node-red available behind some 'weird' url scheme (`/api/hassio_ingress/TOKEN`). This obviously breaks any plugins inside NodeRED that requires a call-back to itself, in case the NodeRED does not know what its 'base url' might be. I'm not yet sure how I can fix that on my side. I'm pretty confident that there are more UI-based node-RED extensions that will break because of this... I did expect to find some user questions about this issue, but couldn't really find any...

Ah darn. Yeah i just looked up what that even was, I guess due to me installing Node-red directly in HA as an add-on it uses hassio-ingress for the implementation. 

As a "quick-fix" for now, I installed Node-red locally on my windows server. HA is running natively in a VM on the same windows server.
copied over my flow and 'select items' came up instantly. I'm glad I have a workaround but I'm going to keep my fingers crossed you find a solution to get it working with node-red that is installed via the HA add-ons :)
I appreciate all the help so far!

![image](https://user-images.githubusercontent.com/35588594/147715113-2dc05f41-e041-49d5-b5e0-e42b6fb189b6.png)

**Comment by MDAR** [comment] 2021-12-31 14:19
Hi

I was slowing reading through this post in the hope that it might resolve the same issue I'm seeing.


To recap (for my own sanity)

Are we suggesting that if the admin page of Node-RED is changed, it will affect the population of the openHAB items list?

FYI

I have a fresh install of OH3 and Node-RED on an Odroid C4

Node-RED is set to

{IP}:1880/admin

nothing strange in OH3, just installed as is.

API token entered into Node-RED openHAB controller.


If I create the Nodes in a Text editor and import them, they work perfectly, in both directions, including the Get node.

So the only thing I can think of is that the `:1880/admin` and `httpStatic` change is the issue.

I'll reset the node-RED `settings.js` file and report back

**Comment by jeroenhendricksen** [comment] 2022-01-01 19:21
> Hi
> 
> I was slowing reading through this post in the hope that it might resolve the same issue I'm seeing.
> 
> To recap (for my own sanity)
> 
> Are we suggesting that if the admin page of Node-RED is changed, it will affect the population of the openHAB items list?
> 
> FYI
> 
> I have a fresh install of OH3 and Node-RED on an Odroid C4, running DietPI
> 
> Node-RED is set to
> 
> {IP}:1880/admin
> 
> nothing strange in OH3, just installed as is.
> 
> API token entered into Node-RED openHAB controller.
> 
> If I create the Nodes in a Text editor and import them, they work perfectly, in both directions, including the Get node.
> 
> So the only thing I can think of is that the `:1880/admin` and `httpStatic` change is the issue.
> 
> I'll reset the node-RED `settings.js` file and report back
> 
> ## 🥳 YES 🎆
> ### I can confirm that it was the change to the admin path and HTTPStatic that caused my issues.
> I'm happy to live with this for now, as it's only on the openHAB instances, but... it would be nice if I can return to the :1880/admin path
> 
> (I'm sure it used to work in previous versions)
> 
> Please let me know what you would like me to test in order to help resolve this
> 
> I have just checked, it is ONLY this part in the `settings.js` file
> 
> ```
> 
>     // By default, the Node-RED UI is available at http://localhost:1880/
>     // The following property can be used to specify a different root path.
>     // If set to false, this is disabled.
> 
> 
> //  httpAdminRoot: '/admin',
> ```
> 
> that affects the population of the openHAB items list

Thank you for sharing what you've found.
You are not using hassio, are you? The hassio setup uses a reverse proxy which mangles with how Node-RED is made available to the end user. 
The option `httpAdminRoot` you are describing for NodeRED changes the relative weburl (effectually being `/` by default). The latest version of this plugin should already take that path into account, because [it references the relative root](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/eb31514c6f9d97af8553a736c69d5be87955c734/77-openhab2.js#L337) path for Node-RED to perform the callback instead of a path prefixed with `/` (which was the previous solution). So whatever httpAdminRoot you set, the callback should "just work".

I've been thinking about a solution that would make a call-back from the Node-RED UI to its API unnecessary, but as far as I though of it now, that would limit it to a single configured openhab controller, which is unacceptable. If anybody has any thoughts of a nice solution (or knows an existing extension making use of it), I'm all ears!

**Comment by MDAR** [comment] 2022-01-05 11:32
Hi @jeroenhendricksen 

I see what you're getting at there
>The option ```httpAdminRoot``` you are describing for NodeRED changes the relative weburl (effectually being / by default). The latest version of this plugin should already take that path into account, because it references the relative root path for Node-RED to perform the callback instead of a path prefixed with / (which was the previous solution). So whatever ```httpAdminRoot``` you set, the callback should "just work". However, when ```httpNodeRoot``` is not also set to the same as ```httpAdminRoot``` (/ is default), the items list won't be populated. It's best to set just the ```httpRoot```, which will change both ```httpAdminRoot``` and ```httpNodeRoot```.

And yes, ONLY setting HttpRoot does move the WHOLE landing page to (for example) ```:1880/red```

But then the Dashboard also moves to ```:1880/red/ui``` so not impossible or even mildly difficult for a user to stumble across the admin page.

Yes, I could also setup credentials for the Admin page, however I struggle enough with getting users to _ONLY_ enter ```:1880/ui```

The setup of having ```:1880/admin``` and ```:1880/ui``` used to work quite happily in version 1.x of Node-RED. (leaving the root of ```:1880``` open for file sharing

In fairness, I tend only use the file sharing part for projects that don't use a lot of openHAB (or any at all) so it wouldn't be a major issue to use different settings, it's just something more for me to remember.

As a thought and purely a "non coder's thought" could an option be added to the controller setup page to cover this edge case?

**Comment by MDAR** [comment] 2022-01-12 19:06
@jeroenhendricksen 

Hi

I am prepping some hardware for a demonstration tomorrow and noticed that the combination of Node-Red, openHAB3 and your Nodes are working with the 1880/admin configuration.

FYI

Nodered version - 1.3.4
openHAB versions - openHAB 3.2.0.M1, Milestone Build
Your nodes - 1.3.25


When I get back from this meeting, I'll double check the combinations that are giving trouble.

Thanks for all your hard work.

Stuart

**Comment by firstascentak** [comment] 2022-01-12 20:15
> @jeroenhendricksen
> 
> Hi
> 
> I am prepping some hardware for a demonstration tomorrow and noticed that the combination of Node-Red, openHAB3 and your Nodes are working with the 1880/admin configuration.
> 
> FYI
> 
> Nodered version - 1.3.4 openHAB versions - openHAB 3.2.0.M1, Milestone Build Your nodes - 1.3.25
> 
> When I get back from this meeting, I'll double check the combinations that are giving trouble.
> 
> Thanks for all your hard work.
> 
> Stuart

I just wanted to quickly add that the latest version of his node is 1.3.29 not ...25. Which may or may not have an affect on your project but figured I'd mention just in case :)

**Comment by jeroenhendricksen** [comment] 2022-01-12 20:32
Hi Stuart,

> I am prepping some hardware for a demonstration tomorrow and noticed that the combination of Node-Red, openHAB3 and your Nodes are working with the 1880/admin configuration.

Are you running the latest 1.3.30 version as @firstascentak mentions?
Maybe [this commit from 1.3.29 to 1.3.30](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/commit/9fdf40257b4fa3563837971973de7f21941e419e) has fixed the problem you were having?

> As a thought and purely a "non coder's thought" could an option be added to the controller setup page to cover this edge case?

The only thing I can do from the node red controls web UI is something that I've already done in 1.3.30: using the `RED.settings.httpNodeRoot` setting to create the callback url. This callback is passing back all of the openhab controller nodes settings which I think is ugly, but I don't really have a better way (and those settings are required for contacting the openhab controller (there can be more than one!) and getting the list of items and groups). I'm thinking of having a look at other node-red modules (like the home assistant ones) to see how they are working. Maybe those developers have found more elegant ways to do this.

I just hope it keeps working for your setup with 1.3.30.

**Comment by MDAR** [comment] 2022-01-13 06:55
Thanks both.


I can confirm that this combination works


Node-RED V2.1.4
openHAB3 nodes V1.3.30

@jeroenhendricksen 
So it looks like your fix has worked.

**Comment by jeroenhendricksen** [comment] 2022-03-23 21:27
I'm closing this issue, because the underlying problem related to `httpNodeRoot` has been fixed. The user(s) who installed NodeRED as a HassIO plugin (that also adds a reverse proxy that causes problems) has not yet been fixed. I've created a separate issue for that: #28

**Closed by jeroenhendricksen** 2022-03-23 21:27 UTC

**Comment by sleugner** [comment] 2023-04-25 15:31
Hi Sorry for replying to the closed topic but this is the only thread where I found the reference to the error "EHOSTUNREACH".
I am Running NodeRed v3.0.2 on a Docker Container in Unraid. Also OpenHAB 3 V. 3.4.3 is running on a Docker in Unraid.
I just migrated from Raspi 4 to Unraid and tried to import my Nodes.
Now I get the error: 
25 Apr 16:28:00 - [warn] [openhab2-controller2:OpenHab] Error: {"type":"error","message":"connect EHOSTUNREACH 192.168.x.xxx:8080"}.

The version of the palette "node-red-contrib-openhab3" is 1.4.9.
I changed the in 77-openhab2.html from
$.getJSON("openhab3/items", config) 
to
$.getJSON("endpoint/openhab3/items", config) 

But that didn't work. Any Idea what I am doing wrong?
